--------- USER SETTING TABLES ---------

CREATE TABLE DBO.DEPARTMENTS (
	DEPARTMENT_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_DEPARTMENT_KEY DEFAULT NEWID(),
	DEPARTMENT NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (DEPARTMENT_KEY)
);

CREATE TABLE DBO.ROLES (
	ROLE_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_ROLE_KEY DEFAULT NEWID(),
	ROLE_NAME NVARCHAR(10) NOT NULL,
	CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_KEY)
);

CREATE TABLE DBO.USERS (
	USER_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_USER_KEY DEFAULT NEWID(),
	USER_NAME VARCHAR(255) NOT NULL,
	PASS_WORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NULL,
	PHONE_NUMBER VARCHAR(100) NULL,
	ROLE_KEY VARCHAR(255) NULL,
	FIRST_NAME NVARCHAR(50) NULL,
	MIDDLE_NAME NVARCHAR(50) NULL,
	LAST_NAME NVARCHAR(50) NULL,
	DEPARTMENT_KEY VARCHAR(255) NULL,
	CONSTRAINT UNIQUE_USER_NAME UNIQUE (USER_NAME),
	CONSTRAINT PK_USERS PRIMARY KEY (USER_KEY)
);

CREATE UNIQUE NONCLUSTERED INDEX UQ_USERS_EMAIL ON DBO.USERS (EMAIL ASC);

ALTER TABLE DBO.USERS ADD CONSTRAINT FK_USERS_DEPARTMENTS FOREIGN KEY (DEPARTMENT_KEY) REFERENCES DBO.DEPARTMENTS(DEPARTMENT_KEY);
ALTER TABLE DBO.USERS ADD CONSTRAINT FK_USERS_ROLES FOREIGN KEY (ROLE_KEY) REFERENCES DBO.ROLES(ROLE_KEY);

--------- BUSINESS TABLES ---------
-- DBO.RECEIPTS:
CREATE TABLE DBO.RECEPITS (
	RECEIPT_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_RECEIPT_KEY DEFAULT NEWID(),
	RECEIPT_CODE CHAR(10) NOT NULL,
	RECEIPT_DATE DATETIME2 NOT NULL,
	SHIPMENT_CODE VARCHAR(10) NOT NULL,
	INVOICE_NUMBER VARCHAR(10) NOT NULL,
	CUSTOMER_KEY VARCHAR(255) NOT NULL,
	CONSTRAINT PK_RECEIPT_KEY PRIMARY KEY (RECEIPT_KEY),
	CONSTRAINT FK_RECEIPTS_CUSTOMERS FOREIGN KEY (CUSTOMER_KEY) REFERENCES DBO.CUSTOMERS (CUSTOMER_KEY)
);

-- DBO.CUSTOMERS:
CREATE TABLE DBO.CUSTOMERS (
	CUSTOMER_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_CUSTOMER_KEY DEFAULT NEWID(),
	TAX_CODE VARCHAR(11) NOT NULL,
	CUSTOMER_NAME NVARCHAR(255) NOT NULL,
	ADDRESS NVARCHAR(255) NULL,
	PROVINCE_KEY VARCHAR(255) NOT NULL,
	START_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
	END_TIME DATETIME2 NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
	CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_KEY),
	CONSTRAINT FK_CUSTOMERS_PROVINCES FOREIGN KEY (PROVINCE_KEY) REFERENCES DBO.PROVINCES(PROVINCE_KEY)
);

-- DBO.PROVINCES:
CREATE TABLE DBO.PROVINCES (
	PROVINCE_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_PROVINCE_KEY DEFAULT NEWID(),
	OLD_PROVINCE NVARCHAR(100) NOT NULL,
	NEW_PROVINCE NVARCHAR(100) NOT NULL,
	ZONE NVARCHAR(100) NULL,
	START_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
	END_TIME DATETIME2 NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
	CONSTRAINT PK_PROVINCES PRIMARY KEY (PROVINCE_KEY)
);

-- DBO.CONTAINERS:
CREATE TABLE DBO.CONTAINERS (
	CONTAINER_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_CONTAINER_KEY DEFAULT NEWID(),
	CONTAINER_SIZE INT NOT NULL,
	CONTAINER_STATUS CHAR(1) NULL,
	CONTAINER_TYPE CHAR(2) NULL,
	START_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
	END_TIME DATETIME2 NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
	CONSTRAINT PK_CONTAINERS PRIMARY KEY (CONTAINER_KEY)
);

-- DBO.SERVICES:
CREATE TABLE DBO.SERVICES (
	SERVICE_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_SERVICE_KEY DEFAULT NEWID(),
	SERVICE_NAME NVARCHAR(100) NOT NULL,
	CONTAINER_KEY VARCHAR(255) NOT NULL,
	FROM_DATE DATETIME2 NULL,
	TO_DATE DATETIME2 NULL,
	UNIT_PRICE INT DEFAULT 0 NULL,
	TAX_RATE INT DEFAULT 0 NULL,
	START_TIME DATETIME2 DEFAULT GETDATE() NOT NULL,
	END_TIME DATETIME2 NULL,
	IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
	CONSTRAINT PK_SERVICES PRIMARY KEY (SERVICE_KEY),
	CONSTRAINT FK_SERVICES_CONTAINERS FOREIGN KEY (CONTAINER_KEY) REFERENCES DBO.CONTAINERS(CONTAINER_KEY)
);

-- DBO.LINES:
CREATE TABLE DBO.LINES (
	LINE_KEY VARCHAR(255) NOT NULL CONSTRAINT UNIQUE_LINE_KEY DEFAULT NEWID(),
	RECEIPT_KEY VARCHAR(255) NOT NULL,
	CONTAINER_NUMBER VARCHAR(11) NOT NULL,
	SERVICE_KEY VARCHAR(255) NOT NULL,
	QUANTITY INT,
	DISCOUNT INT,
	AMOUNT INT,
	CONSTRAINT PK_LINE PRIMARY KEY (LINE_KEY),
	CONSTRAINT FK_LINE_RECEIPTS FOREIGN KEY (RECEIPT_KEY) REFERENCES DBO.RECEIPTS (RECEIPT_KEY),
	CONSTRAINT FK_LINE_SERVICES FOREIGN KEY (SERVICE_KEY) REFERENCES DBO.SERVICES (SERVICE_KEY)
);